apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.11.2
    helm:
      values: |
        controller:
          extraArgs:
            enable-ssl-passthrough: true
          replicaCount: 2
          nodeSelector:
            kubernetes.io/os: linux
          admissionWebhooks:
            enabled: false
          service:
            type: LoadBalancer
            externalTrafficPolicy: Local
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
