apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.23.0
    helm:
      values: |
        global:
          enabled: true
          tlsDisable: true
        server:
          ingress:
            enabled: true
            activeService: false
            ingressClassName: nginx
            hosts:
              - host: vault.host.tanghome.us
                paths:
                  - /
            tls:
              - secretName: vault-tls
                hosts:
                  - vault.host.tanghome.us
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          dataStorage:
            enabled: true
            storageClass: "nfs-provisioner"
            size: 10Gi
          ha:
            enabled: true
            raft:
              enabled: true
              setNodeId: true
            config: |
              ui = true
              listener "tcp" {
                address = "[::]:8200"
                cluster_address = "[::]:8201"
              }
              storage "raft" {
                path = "/vault/data"
                retry_join {
                  leader_api_addr = "https://vault-helm-0.vault-helm-internal:8200"
                }
                retry_join {
                  leader_api_addr = "https://vault-helm-1.vault-helm-internal:8200"
                }
                retry_join {
                  leader_api_addr = "https://vault-helm-2.vault-helm-internal:8200"
                }
              }
              service_registration "kubernetes" {}
        ui:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
