apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.29.0
    helm:
      values: |
        server:
          logLevel: "debug"
          ingress:
            enabled: true
            activeService: true
            ingressClassName: nginx
            hosts:
              - host: vault.host.tanghome.us
                paths:
                  - /
            tls:
              - secretName: vault-tls
                hosts:
                  - vault.host.tanghome.us
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          dataStorage:
            enabled: true
            storageClass: "nfs-provisioner"
            size: 10Gi
          ha:
            enabled: true
            apiAddr: https://vault.host.tanghome.us
            raft:
              enabled: true
              setNodeId: true
              config: |
                ui = true
                listener "tcp" {
                  tls_disable = true
                  address = "[::]:8200"
                  cluster_address = "[::]:8201"
                  tls_disable_client_certs = true
                }
                storage "raft" {
                  path = "/vault/data"
                  retry_join {
                    leader_api_addr = "https://vault-helm-0.vault-helm-internal:8200"
                  }
                  retry_join {
                    leader_api_addr = "https://vault-helm-1.vault-helm-internal:8200"
                  }
                  retry_join {
                    leader_api_addr = "https://vault-helm-2.vault-helm-internal:8200"
                  }
                }
                service_registration "kubernetes" {}
          serviceAccount:
            createSecret: true
            annotations:
              kubernetes.io/service-account.name: "vault-helm"
        ui:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
