apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-external-provisioner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    chart: nfs-subdir-external-provisioner
    targetRevision: 4.0.18
    helm:
      values: |
        nfs:
          server: 10.0.0.4
          path: /mnt/Lab/nfs-provisioner
        storageClass:
          name: nfs-provisioner
          defaultClass: true
          provisionerName: k8s-sigs.io/nfs-subdir-external-provisioner
          reclaimPolicy: Retain
          allowVolumeExpansion: true
          accessModes: ReadWriteMany
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-provisioner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
