apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-vcluster
  namespace: argocd
spec:
  project: default
  source:
    chart: vcluster
    repoURL: https://charts.loft.sh
    targetRevision: 0.20.0-beta.5
    helm:
      releaseName: test-vcluster
  destination:
    server: https://kubernetes.default.svc
    namespace: test-vcluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/warn: privileged
        pod-security.kubernetes.io/audit: privileged
