apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: https://vault.host.tanghome.us
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: /v1/auth/kubernetes
          role: external-secrets
          serviceAccountRef:
            name: external-secrets
