apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-agent-credentials
  namespace: grafana
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: grafana-agent-credentials
  data:
  - secretKey: prometheus-host
    remoteRef:
      key: kv/grafana-agent
  - secretKey: prometheus-user
    remoteRef:
      key: kv/grafana-agent
  - secretKey: loki-host
    remoteRef:
      key: kv/grafana-agent
  - secretKey: loki-user
    remoteRef:
      key: kv/grafana-agent
  - secretKey: tempo-host
    remoteRef:
      key: kv/grafana-agent
  - secretKey: tempo-user
    remoteRef:
      key: kv/grafana-agent
  - secretKey: access-policy-token
    remoteRef:
      key: kv/grafana-agent
