apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-agent-credentials
  namespace: k8s-monitoring
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-agent-credentials
  data:
  - secretKey: prometheus-host
    remoteRef:
      key: kv/grafana-agent/prometheus-host
  - secretKey: prometheus-user
    remoteRef:
      key: kv/grafana-agent/prometheus-user
  - secretKey: loki-host
    remoteRef:
      key: kv/grafana-agent/loki-host
  - secretKey: loki-user
    remoteRef:
      key: kv/grafana-agent/loki-user
  - secretKey: tempo-host
    remoteRef:
      key: kv/grafana-agent/tempo-host
  - secretKey: tempo-user
    remoteRef:
      key: kv/grafana-agent/tempo-user
  - secretKey: access-policy-token
    remoteRef:
      key: kv/grafana-agent/access-policy-token
