apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://bjw-s.github.io/helm-charts/
    targetRevision: 3.3.2
    chart: app-template
    helm:
      values: |
        controllers:
          home-assistant:
            annotations:
              reloader.stakater.com/auto: "true"
            containers:
              home-assistant:
                image:
                  repository: ghcr.io/home-assistant/home-assistant
                  tag: 2024.7.4
                env:
                  TZ: "America/Los_Angeles"
                  # SECRET_RECORDER_DB_URL:
                  #   valueFrom:
                  #     secretKeyRef:
                  #       name: database-homeassistant-user
                  #       key: POSTGRES_URL
                probes:
                  liveness:
                    enabled: true
                    custom: true
                    spec:
                      httpGet:
                        path: /
                        port: 80
                      initialDelaySeconds: 0
                      periodSeconds: 10
                      timeoutSeconds: 5
                      failureThreshold: 5
                  readiness:
                    enabled: true
                    custom: true
                    spec:
                      httpGet:
                        path: /
                        port: 80
                      initialDelaySeconds: 0
                      periodSeconds: 10
                      timeoutSeconds: 5
                      failureThreshold: 5
                  # startup:
                  #   enabled: true
                  #   custom: true
                  #   spec:
                  #     httpGet:
                  #       path: /
                  #       port: 80
                  #     initialDelaySeconds: 0
                  #     periodSeconds: 5
                  #     timeoutSeconds: 5
                  #     failureThreshold: 30

                resources:
                  requests:
                    cpu: 100m
                    memory: 500M
                  limits:
                    memory: 1000M


        service:
          home-assistant:
            ports:
              http:
                port: 8123

        ingress:
          home-assistant:
            enabled: true
            className: nginx
            hosts:
              - host: home-assistant.host.tanghome.us
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      name: home-assistant-helm
                      port: http

        persistence:
          config:
            enabled: true
            type: persistentVolumeClaim
            storageClass: nfs-provisioner
            accessMode: ReadWriteOnce
            size: 1Gi

        metrics:
          enabled: true
          serviceMonitor:
            interval: 1m

        addons:
          codeserver:
            enabled: true
            image:
              repository: codercom/code-server
              tag: 4.19.1
            workingDir: "/config"
            args:
              - --auth
              - "none"
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"
            volumeMounts:
              - name: config
                mountPath: /config

        configmap:
          config:
            enabled: true
            data:
              configuration.yaml: |
                http:
                  use_x_forwarded_for: true
                  trusted_proxies:
                    - 10.0.0.0/8
                    - 172.16.0.0/12
                    - 192.168.0.0/16

  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
