apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DarrellTang/argocd-multi-cluster.git
    targetRevision: HEAD
    path: host/metallb
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  syncStrategy:
    hook:
      postSync:
        - name: metallb-crds
          type: Sync
          hooks:
          - events: ["PostSync"]
            manifestPath: host/metallb/crds
  ignoreDifferences:
  - group: metallb.io
    kind: L2Advertisement
    jsonPointers:
    - /spec/ipAddressPools
  - group: argoproj.io
    kind: Application
    jsonPointers:
    - /spec/source/targetRevision
