apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DarrellTang/argocd-multi-cluster.git
    targetRevision: HEAD
    path: host/nfs-provisioner
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
