apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-csi-provisioner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    targetRevision: v4.1.0
    chart: csi-driver-nfs
    helm:
      values: |
        nfs:
          server: 10.0.0.4
          path: /mnt/Lab/csi-driver-nfs
        storageClass:
          name: nfs-csi
          defaultClass: true
          reclaimPolicy: Retain
          volumeBindingMode: Immediate
          allowVolumeExpansion: true
  destination:
    server: https://kubernetes.default.svc
    namespace: csi-driver-nfs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
