apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token-secret
    creationPolicy: Owner
  data:
  - secretKey: api-token
    remoteRef:
      key: 3ad695b4-4dab-4fc1-a7f6-aeda0173a6d9
      property: cloudflare-api-token
